[package]
name = "rolling-buffer"
version = "0.1.0"
edition = "2024"
authors = ["Artyom Baryshnikov"]
license-file = "LICENSE"
keywords = ["buffer", "circular", "rolling", "util"]
readme = "README.md"
repository = "https://github.com/ArtyomBA/rolling-buffer"
[dependencies]
